import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/client.ts',
    'src/encryption.ts',
    'src/field-encryption.ts',
    'src/api.ts',
    'src/query.ts',
    'src/mutation.ts',
    'src/hooks.ts',
    'src/query-client.ts',
    'src/prefetch.ts',
    'src/query-options.ts',
    'src/sse.ts',
    'src/tab-leader.ts',
    'src/ws.ts',
    'src/upload.ts',
    'src/cache.ts',
    'src/presets/soft-delete.ts',
    'src/presets/history.ts',
    'src/presets/bulk.ts',
    'src/presets/slug.ts',
    'src/presets/tree.ts',
    'src/presets/search.ts',
  ],
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outDir: 'dist',
  clean: true,
  sourcemap: false,
  dts: true,
  unbundle: true,
  treeshake: true,
  minify: false,
  deps: {
    neverBundle: [
      'react',
      'react/jsx-runtime',
      '@tanstack/react-query',
      'jose',
    ],
  },
});
